### ISSUE TITLE
Radio Button is not drawing properly

### ISSUE THREAD

**Issue by yashadmiral** [igormironchik/prototyper#1]
To regenerate steps.

Issue 1. 
1. Add the Page.
2. select the Draw radio Button.
3. click in drawing area. ( radio button is not drawing completely.  some  portion will cut. )

Issue 2.
1. Add the Page.
2. select the Draw radio Button.
3. click in drawing area and drag ( radio button is drawing completely. But label is cut from bottom  and  Top.)

**Comment by igormironchik** [comment]
Could you provide screenshot of the second issue?

> But label is cut from bottom and Top.

I don't see this issue.

**Comment by yashadmiral** [comment]
Issue 1.
![image](https://user-images.githubusercontent.com/35041062/71562375-13190580-2a3d-11ea-82b2-aeaf75105c32.png)


issue 2.
![image](https://user-images.githubusercontent.com/35041062/71562309-bddcf400-2a3c-11ea-8586-d54f29c1b909.png)


if mouse pointer is leave the drawing area then issue 1 is solve.

**Comment by igormironchik** [comment]
Not sure about sub-issue 2 of this issue, can't reproduce it here, but I changed default size, placing with just a click, etc...

**Comment by igormironchik** [comment]
Got sub-issue 2...
