### ISSUE TITLE
Draw Spin box and ok button is transparent.  

### ISSUE THREAD

**Issue by yashadmiral** [igormironchik/prototyper#3]
Background Text is  showing in spinbox.

Firstly I select the insert text and write some text on drawing area.
after that if I will select the spinbox and put top of that text  then text is showing in spin box.

**Comment by igormironchik** [comment]
I don't consider this as an issue, but only at this point of time. All items on drawing area are transparent to each other at this time. This done by design. But can be an issue in the future if I will decide to add background for the items like buttons, spinboxes, rectangles...
