### ISSUE TITLE
Widget are draw outside the drawing area.

### ISSUE THREAD

**Issue by yashadmiral** [igormironchik/prototyper#5]
For regenerate Steps.

1. select any widget.
2. Keep mouse pointer inside the drawing area  and press the mouse button and drag it.
3. It will draw half portion of widget inside the drawing area and half portion of widget outside the drawing area.

**Comment by igormironchik** [comment]
I don't consider this as an issue at this point point of time. All items can be drawn outside page, can be moved outside. They just won't be visible in exported documents, but it's allowed to draw outside. Maybe I will add feature to resize drawing area to fit all items, not sure yet.
